[package]
name = "verification-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow            = { workspace = true }
ark-ff            = { workspace = true }
base64            = { workspace = true }
juniper           = { workspace = true }
ledger            = { workspace = true, features = ["network"] }
mina-core         = { path = "../core" }
mina-curves       = { workspace = true }
mina-node-native  = { workspace = true }
mina-p2p-messages = { workspace = true }
rsexp             = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }